# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - test
  # - trivy file scan
  - build
  - deploy
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

# stages:
#   - trivy file scan
#   # - trivy image scan

# Trivy-file-scan:
#   stage: trivy file scan
#   image:
#     name: aquasec/trivy:latest
#     entrypoint: [""]
#   script:
#     - trivy fs . 

docker-build:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: build
  script:
    - aws --version
    - docker --version
    - echo Login AWS ${AWS_DEFAULT_REGION} ${CI_AWS_ECR_REPOSITORY_URL}/comentarios-api:latest 
    - aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "$CI_AWS_ECR_REPOSITORY_URL"
    - echo "Building image for ${CI_COMMIT_TAG}"
    - docker build -t ${CI_AWS_ECR_REPOSITORY_URL}/comentarios-api:latest .
    - echo "Pushing image..."
    # - docker push ${CI_AWS_ECR_REPOSITORY_URL}:${CI_COMMIT_TAG}
    - docker push ${CI_AWS_ECR_REPOSITORY_URL}/comentarios-api:latest
  only:
    - dev

deploy-aws-fargate:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - echo ${CI_AWS_ECR_REPOSITORY_URL}/comentarios-api:latest
    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$CI_AWS_ECS_TASK_DEFINITION" --region "${AWS_DEFAULT_REGION}")
    - echo ${TASK_DEFINITION}
    - NEW_CONTAINER_DEFINTIION=$(echo $CI_AWS_ECS_TASK_DEFINITION | jq --arg IMAGE "${CI_AWS_ECR_REPOSITORY_URL}/comentarios-api:latest" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
    - echo "Registering new container definition..."
    - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --family "${CI_AWS_ECS_TASK_DEFINITION}" --container-definitions "${NEW_CONTAINER_DEFINTIION}"
    - echo "Updating the service..."
    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${CI_AWS_ECS_CLUSTER}" --service "${CI_AWS_ECS_SERVICE}"  --task-definition "${CI_AWS_ECS_TASK_DEFINITION}"
  only:
    - dev



# Scan-image:
#   stage: trivy image scan
#   image:
#     name: aquasec/trivy:latest
#     entrypoint: [""]
#   script:
#     - echo $CCI_AWS_ECR_REPOSITORY_URLL:$IMAGE_TAG
#     - trivy image $CI_AWS_ECR_REPOSITORY_URL:$IMAGE_TAG


# include:
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: AWS/Deploy-ECS.gitlab-ci.yml


# CI_AWS_ECS_CLUSTER
# CI_AWS_ECS_SERVICE
# CI_AWS_ECR_REPOSITORY_URL
# CI_AWS_ECS_TASK_DEFINITION
